[package]
name = "md-tangle-engine"
version = "0.1.4"
authors = ["Xie Yuheng <xyheme@gmail.com>"]
edition = "2018"
description = """
To tangle markdown.
- the engine of the commend line tool.
"""
license = "GPL-3.0"

[dependencies]
