[package]
name = "org-book"
version = "0.1.0"
authors = ["Xie Yuheng <xyheme@gmail.com>"]
edition = "2018"
description = """
Create book from org-mode files.
"""
license = "GPL-3.0"

[dependencies]
org-parser = { version = "0.1", path = "../org-parser" }